import { Flashcard } from './types';

export const FLASHCARDS: Flashcard[] = [
  { id: 'fc-adequate', term: 'Adequate Security', def: 'Security commensurate with the risk and magnitude of harm from loss/misuse of information.', domain: 'D1' },
  { id: 'fc-admincontrols', term: 'Administrative Controls', def: 'Policies, procedures, training, and management oversight — the "people and process" controls.', domain: 'D1' },
  { id: 'fc-asset', term: 'Asset', def: 'Anything of value to the organization — data, hardware, people, reputation.', domain: 'D1' },
  { id: 'fc-authn', term: 'Authentication', def: 'Verifying that an entity is who or what it claims to be.', domain: 'D3' },
  { id: 'fc-authz', term: 'Authorization', def: 'Granting an authenticated entity permission to perform an action on a resource.', domain: 'D3' },
  { id: 'fc-availability', term: 'Availability', def: 'Ensuring authorized users have timely, reliable access to data and systems.', domain: 'D1' },
  { id: 'fc-baseline', term: 'Baseline', def: 'A documented, agreed reference configuration used to evaluate change/drift.', domain: 'D5' },
  { id: 'fc-biometric', term: 'Biometric', def: '"Something you are" — fingerprint, face, retina, voice — used as an auth factor.', domain: 'D3' },
  { id: 'fc-bot', term: 'Bot', def: 'Automated software agent; often a member of a botnet used for DDoS or credential stuffing.', domain: 'D1' },
  { id: 'fc-classified', term: 'Classified Information', def: 'Data labeled per a classification scheme requiring handling rules per label.', domain: 'D5' },
  { id: 'fc-conf', term: 'Confidentiality', def: 'Preventing unauthorized disclosure of information.', domain: 'D1' },
  { id: 'fc-criticality', term: 'Criticality', def: 'How essential an asset or process is to the organization’s mission.', domain: 'D2' },
  { id: 'fc-integrity', term: 'Data Integrity', def: 'Assurance that data has not been improperly modified — accuracy and completeness preserved.', domain: 'D1' },
  { id: 'fc-encryption', term: 'Encryption', def: 'Converting plaintext into ciphertext using an algorithm and key, reversible with the right key.', domain: 'D5' },
  { id: 'fc-gdpr', term: 'GDPR', def: 'EU General Data Protection Regulation — privacy rights for EU residents; large fines for violations.', domain: 'D1' },
  { id: 'fc-governance', term: 'Governance', def: 'The framework of policies, roles, and processes that steer security decisions and align with goals.', domain: 'D1' },
  { id: 'fc-hipaa', term: 'HIPAA', def: 'US law protecting Protected Health Information (PHI) handled by covered entities.', domain: 'D1' },
  { id: 'fc-impact', term: 'Impact', def: 'The magnitude of harm that would result if a risk materialized.', domain: 'D1' },
  { id: 'fc-isr', term: 'Information Security Risk', def: 'The potential for unauthorized use, disclosure, disruption, or destruction of info to cause harm.', domain: 'D1' },
  { id: 'fc-int', term: 'Integrity', def: 'Property of accuracy and completeness; data and systems are not improperly modified.', domain: 'D1' },
  { id: 'fc-iso', term: 'ISO', def: 'International Organization for Standardization — publishes standards (e.g., ISO/IEC 27001).', domain: 'D1' },
  { id: 'fc-ietf', term: 'IETF', def: 'Internet Engineering Task Force — publishes RFCs that define Internet protocols.', domain: 'D4' },
  { id: 'fc-likelihood', term: 'Likelihood', def: 'Probability that a given threat will exploit a vulnerability.', domain: 'D1' },
  { id: 'fc-mfa', term: 'MFA', def: 'Multi-Factor Authentication — at least two of: know, have, are.', domain: 'D3' },
  { id: 'fc-nist', term: 'NIST', def: 'US National Institute of Standards and Technology — publishes the CSF and SP 800 series.', domain: 'D1' },
  { id: 'fc-nonrep', term: 'Non-repudiation', def: 'Assurance the actor cannot credibly deny the action — typically via digital signatures.', domain: 'D1' },
  { id: 'fc-pii', term: 'PII', def: 'Personally Identifiable Information — data that can identify a specific individual.', domain: 'D1' },
  { id: 'fc-phi', term: 'PHI', def: 'Protected Health Information — individually identifiable health data covered by HIPAA.', domain: 'D1' },
  { id: 'fc-phys', term: 'Physical Controls', def: 'Tangible safeguards — locks, badges, guards, CCTV, fences, mantraps.', domain: 'D3' },
  { id: 'fc-privacy', term: 'Privacy', def: 'Right of individuals to control collection and use of their personal information.', domain: 'D1' },
  { id: 'fc-risk', term: 'Risk', def: 'Potential for loss when a threat exploits a vulnerability; function of likelihood and impact.', domain: 'D1' },
  { id: 'fc-r-accept', term: 'Risk Acceptance', def: 'Decision to take no action; live with the risk because cost/effort to treat is not justified.', domain: 'D1' },
  { id: 'fc-r-assess', term: 'Risk Assessment', def: 'Identifying, analyzing, and evaluating risk — input to treatment decisions.', domain: 'D1' },
  { id: 'fc-r-avoid', term: 'Risk Avoidance', def: 'Removing the activity or asset that creates the risk.', domain: 'D1' },
  { id: 'fc-r-mit', term: 'Risk Mitigation', def: 'Reducing likelihood or impact by applying controls; most common treatment.', domain: 'D1' },
  { id: 'fc-r-tx', term: 'Risk Transfer', def: 'Shifting impact to a third party — insurance, contracts, outsourcing.', domain: 'D1' },
  { id: 'fc-qual', term: 'Qualitative Risk Analysis', def: 'Subjective labels (High/Medium/Low) prioritizing risks fast without numeric values.', domain: 'D1' },
  { id: 'fc-quant', term: 'Quantitative Risk Analysis', def: 'Numeric estimates of likelihood and impact (e.g., ALE, SLE, ARO).', domain: 'D1' },
  { id: 'fc-soceng', term: 'Social Engineering', def: 'Manipulating people into divulging info or performing actions that compromise security.', domain: 'D4' },
  { id: 'fc-subject', term: 'Subject', def: 'Active entity (user, process, device) that requests access to an object.', domain: 'D3' },
  { id: 'fc-object', term: 'Object', def: 'Passive resource (file, system, database) that a subject may access.', domain: 'D3' },
  { id: 'fc-leastpriv', term: 'Least Privilege', def: 'Grant only the minimum access needed to perform a role or task.', domain: 'D3' },
  { id: 'fc-sod', term: 'Separation of Duties', def: 'Split critical actions across multiple people to prevent fraud and unilateral errors.', domain: 'D3' },
  { id: 'fc-dac', term: 'DAC', def: 'Discretionary Access Control — owner decides who can access their resources.', domain: 'D3' },
  { id: 'fc-mac', term: 'MAC', def: 'Mandatory Access Control — system enforces labels/classification; users cannot override.', domain: 'D3' },
  { id: 'fc-rbac', term: 'RBAC', def: 'Role-Based Access Control — permissions tied to roles, users assigned to roles.', domain: 'D3' },
  { id: 'fc-osi', term: 'OSI Model', def: '7-layer reference model: Physical, Data Link, Network, Transport, Session, Presentation, Application.', domain: 'D4' },
  { id: 'fc-firewall', term: 'Firewall', def: 'Network device or software that enforces an access policy between networks of different trust levels.', domain: 'D4' },
  { id: 'fc-ids', term: 'IDS', def: 'Intrusion Detection System — alerts on suspicious activity; does not block.', domain: 'D4' },
  { id: 'fc-ips', term: 'IPS', def: 'Intrusion Prevention System — in-line; actively blocks malicious traffic.', domain: 'D4' },
  { id: 'fc-vpn', term: 'VPN', def: 'Virtual Private Network — encrypted tunnel across an untrusted network.', domain: 'D4' },
  { id: 'fc-symenc', term: 'Symmetric Encryption', def: 'Same key encrypts and decrypts — fast; key distribution is the challenge. AES, DES.', domain: 'D5' },
  { id: 'fc-asymenc', term: 'Asymmetric Encryption', def: 'Key pair: public encrypts/verifies, private decrypts/signs. RSA, ECC.', domain: 'D5' },
  { id: 'fc-hash', term: 'Hashing', def: 'One-way function producing a fixed-size digest; verifies integrity. SHA-256, not MD5.', domain: 'D5' },
  { id: 'fc-class', term: 'Data Classification', def: 'Labeling data by sensitivity to drive protection requirements.', domain: 'D5' },
  { id: 'fc-destroy', term: 'Data Destruction', def: 'Rendering data unrecoverable: clearing (overwrite), purging (degauss), physical destruction.', domain: 'D5' },
  { id: 'fc-harden', term: 'Hardening', def: 'Reducing attack surface — patch, disable unused services, restrict accounts, secure configs.', domain: 'D5' },
  { id: 'fc-logging', term: 'Logging', def: 'Recording events to enable monitoring, accountability, and forensic investigation.', domain: 'D5' },
  { id: 'fc-patch', term: 'Patch Management', def: 'Process of identifying, testing, and applying software updates to remediate vulnerabilities.', domain: 'D5' },
  { id: 'fc-zerotrust', term: 'Zero Trust', def: 'Never trust, always verify — no implicit trust based on network location.', domain: 'D4' },
  { id: 'fc-rpo', term: 'RPO', def: 'Recovery Point Objective — maximum acceptable data loss measured in time.', domain: 'D2' },
  { id: 'fc-rto', term: 'RTO', def: 'Recovery Time Objective — maximum acceptable downtime before recovery is complete.', domain: 'D2' },
];

export const FLASHCARDS_BY_DOMAIN = FLASHCARDS.reduce<Record<string, Flashcard[]>>((acc, c) => {
  (acc[c.domain] ||= []).push(c);
  return acc;
}, {});
