import { Flashcard } from './types';

// Glossary / flashcards — every entry must reference a real OBJECTIVES id (validated by scripts/validate-content.ts).
export const FLASHCARDS: Flashcard[] = [
  // ============================================================
  // D1 — Security Principles
  // ============================================================
  { id: 'fc-conf', term: 'Confidentiality', def: 'Preventing unauthorized disclosure of information.', domain: 'D1', subObjective: 'D1.CIA.Definition' },
  { id: 'fc-int', term: 'Integrity', def: 'Property of accuracy and completeness — data and systems are not improperly modified.', domain: 'D1', subObjective: 'D1.CIA.Definition' },
  { id: 'fc-availability', term: 'Availability', def: 'Ensuring authorized users have timely, reliable access to data and systems.', domain: 'D1', subObjective: 'D1.CIA.Definition' },
  { id: 'fc-cia', term: 'CIA Triad', def: 'Confidentiality, Integrity, Availability — the three foundational security goals.', domain: 'D1', subObjective: 'D1.CIA.Definition' },
  { id: 'fc-dad', term: 'DAD', def: 'Disclosure, Alteration, Destruction — the threat-side mirror of CIA.', domain: 'D1', subObjective: 'D1.CIA.DAD' },
  { id: 'fc-integrity-data', term: 'Data Integrity', def: 'Assurance that data has not been improperly modified; accuracy and completeness preserved.', domain: 'D1', subObjective: 'D1.CIA.Definition' },
  { id: 'fc-pii', term: 'PII', def: 'Personally Identifiable Information — data that can identify a specific individual.', domain: 'D1', subObjective: 'D1.DataTypes.PII' },
  { id: 'fc-phi', term: 'PHI', def: 'Protected Health Information — individually identifiable health data covered by HIPAA.', domain: 'D1', subObjective: 'D1.DataTypes.PHI' },
  { id: 'fc-spi', term: 'SPI', def: 'Sensitive Personal Information — special-category data (race, religion, sexual orientation, health, genetic, biometric).', domain: 'D1', subObjective: 'D1.DataTypes.SPI' },
  { id: 'fc-quasi-id', term: 'Quasi-identifier', def: 'A data field that is not unique alone but can identify someone when combined with others (e.g., ZIP + DOB + gender).', domain: 'D1', subObjective: 'D1.DataTypes.PII' },
  { id: 'fc-deident', term: 'De-identification', def: 'Removing or transforming PII so individuals cannot be readily identified.', domain: 'D1', subObjective: 'D1.DataTypes.PII' },
  { id: 'fc-pseudo', term: 'Pseudonymization', def: 'Replacing identifying fields with reversible tokens; still considered personal data under GDPR.', domain: 'D1', subObjective: 'D1.DataTypes.PII' },
  { id: 'fc-risk', term: 'Risk', def: 'Potential for loss when a threat exploits a vulnerability; function of likelihood and impact.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-likelihood', term: 'Likelihood', def: 'Probability that a given threat will exploit a vulnerability.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-impact', term: 'Impact', def: 'Magnitude of harm that would result if a risk materialized.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-residual', term: 'Residual Risk', def: 'Risk that remains after controls are applied.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-inherent', term: 'Inherent Risk', def: 'The risk level before any controls are applied.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-r-accept', term: 'Risk Acceptance', def: 'Decision to take no action; live with the risk because cost to treat is not justified.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-r-assess', term: 'Risk Assessment', def: 'Identifying, analyzing, and evaluating risk — input to treatment decisions.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-r-avoid', term: 'Risk Avoidance', def: 'Removing the activity or asset that creates the risk.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-r-mit', term: 'Risk Mitigation', def: 'Reducing likelihood or impact by applying controls; most common treatment.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-r-tx', term: 'Risk Transfer', def: 'Shifting impact to a third party — insurance, contracts, outsourcing.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-qual', term: 'Qualitative Risk Analysis', def: 'Subjective labels (High/Medium/Low) prioritizing risks fast without numeric values.', domain: 'D1', subObjective: 'D1.Risk.Qualitative' },
  { id: 'fc-quant', term: 'Quantitative Risk Analysis', def: 'Numeric estimates of likelihood and impact (e.g., ALE, SLE, ARO, EF).', domain: 'D1', subObjective: 'D1.Risk.Quantitative' },
  { id: 'fc-ale', term: 'ALE', def: 'Annualized Loss Expectancy = SLE × ARO. Expected dollar loss per year.', domain: 'D1', subObjective: 'D1.Risk.Quantitative' },
  { id: 'fc-sle', term: 'SLE', def: 'Single Loss Expectancy = Asset Value × Exposure Factor. Loss from one event.', domain: 'D1', subObjective: 'D1.Risk.Quantitative' },
  { id: 'fc-aro', term: 'ARO', def: 'Annualized Rate of Occurrence — events per year (e.g., 0.1 = once every 10 years).', domain: 'D1', subObjective: 'D1.Risk.Quantitative' },
  { id: 'fc-ef', term: 'Exposure Factor', def: 'Percentage of asset value lost in a single event (0.0–1.0).', domain: 'D1', subObjective: 'D1.Risk.Quantitative' },
  { id: 'fc-asset', term: 'Asset', def: 'Anything of value to the organization — data, hardware, people, reputation.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-vulnerability', term: 'Vulnerability', def: 'A weakness that can be exploited by a threat to cause harm.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-threat', term: 'Threat', def: 'Anything that could intentionally or accidentally exploit a vulnerability.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-exploit', term: 'Exploit', def: 'Technique or code that takes advantage of a specific vulnerability.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-isr', term: 'Information Security Risk', def: 'Potential for unauthorized use, disclosure, disruption, or destruction of information.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-criticality', term: 'Criticality', def: 'How essential an asset or process is to the organization\'s mission.', domain: 'D1', subObjective: 'D1.Risk.Formula' },
  { id: 'fc-admincontrols', term: 'Administrative Controls', def: 'Policies, procedures, training, and management oversight — the "people and process" controls.', domain: 'D1', subObjective: 'D1.Controls.Categories' },
  { id: 'fc-techcontrols', term: 'Technical Controls', def: 'Hardware/software controls — firewalls, encryption, MFA, antivirus, access control lists.', domain: 'D1', subObjective: 'D1.Controls.Categories' },
  { id: 'fc-phys', term: 'Physical Controls', def: 'Tangible safeguards — locks, badges, guards, CCTV, fences, mantraps.', domain: 'D1', subObjective: 'D1.Controls.Categories' },
  { id: 'fc-preventive', term: 'Preventive Control', def: 'Stops an action from occurring (e.g., locked door, firewall block rule).', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-detective', term: 'Detective Control', def: 'Identifies that an event occurred (e.g., logs, IDS alerts, motion sensors).', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-corrective', term: 'Corrective Control', def: 'Restores systems or processes after an incident (e.g., backup restore, patch).', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-deterrent', term: 'Deterrent Control', def: 'Discourages an attacker from acting (e.g., visible cameras, warning signs).', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-compensating', term: 'Compensating Control', def: 'Substitutes for a required control that cannot be implemented as designed.', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-directive', term: 'Directive Control', def: 'Instructs people what to do (policies, procedures, signage).', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-recovery', term: 'Recovery Control', def: 'A type of corrective control focused on restoring service or data after a loss.', domain: 'D1', subObjective: 'D1.Controls.Functions' },
  { id: 'fc-defense-depth', term: 'Defense in Depth', def: 'Layered controls — physical, technical, administrative — so failure of one is not catastrophic.', domain: 'D3', subObjective: 'D3.DefenseInDepth' },
  { id: 'fc-governance', term: 'Governance', def: 'Framework of policies, roles, and processes that steer security decisions and align with goals.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-regulation', term: 'Regulation', def: 'Government-mandated rule that an organization must follow; top of governance hierarchy.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-standard', term: 'Standard', def: 'Specific mandatory requirements implementing policy intent (e.g., AES-256 for data at rest).', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-policy', term: 'Policy', def: 'High-level statement of management intent and security expectations.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-procedure', term: 'Procedure', def: 'Step-by-step instructions for performing a specific task.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-guideline', term: 'Guideline', def: 'Recommended (non-mandatory) practice supporting policies and standards.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-baseline-policy', term: 'Baseline (policy)', def: 'Minimum required level of security for a system or process.', domain: 'D1', subObjective: 'D1.Governance.Hierarchy' },
  { id: 'fc-nist-csf', term: 'NIST CSF', def: 'NIST Cybersecurity Framework — five core functions: Identify, Protect, Detect, Respond, Recover.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-iso-27001', term: 'ISO/IEC 27001', def: 'International standard specifying requirements for an Information Security Management System (ISMS); certifiable.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-iso-27002', term: 'ISO/IEC 27002', def: 'Companion to 27001 — implementation guidance for the controls in Annex A.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-soc1', term: 'SOC 1', def: 'AICPA report on controls over financial reporting at a service organization.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-soc2', term: 'SOC 2', def: 'AICPA report on Trust Services Criteria (Security, Availability, Confidentiality, Processing Integrity, Privacy).', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-soc3', term: 'SOC 3', def: 'Public-distribution version of SOC 2 — high-level pass/fail summary.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-soc2-type1', term: 'SOC 2 Type 1', def: 'Attests to design of controls at a single point in time.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-soc2-type2', term: 'SOC 2 Type 2', def: 'Attests to design AND operating effectiveness of controls over a period (typically 6–12 months).', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-cobit', term: 'COBIT', def: 'ISACA framework for IT governance and management.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-itil', term: 'ITIL', def: 'IT service management framework — incident, problem, change, release management.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-iso', term: 'ISO', def: 'International Organization for Standardization — publishes consensus standards.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-ietf', term: 'IETF', def: 'Internet Engineering Task Force — publishes RFCs that define Internet protocols.', domain: 'D4', subObjective: 'D4.TCPIP' },
  { id: 'fc-nist', term: 'NIST', def: 'US National Institute of Standards and Technology — publishes CSF and the SP 800 series.', domain: 'D1', subObjective: 'D1.Governance.Frameworks' },
  { id: 'fc-insider', term: 'Insider Threat', def: 'Authorized internal user who misuses access — intentionally or accidentally.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-outsider', term: 'Outsider', def: 'External actor without authorized access attempting to breach controls.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-nation-state', term: 'Nation-State Actor', def: 'Government-sponsored attacker pursuing strategic objectives; well-resourced, persistent.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-hacktivist', term: 'Hacktivist', def: 'Attacker motivated by political, social, or ideological causes.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-cybercriminal', term: 'Cybercriminal', def: 'Financially motivated attacker — ransomware, fraud, theft, extortion.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-bot', term: 'Bot', def: 'Automated agent — often member of a botnet — used for DDoS, scanning, or credential stuffing.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-script-kiddie', term: 'Script Kiddie', def: 'Low-skill attacker using prebuilt tools; pursues notoriety or thrill.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-apt', term: 'APT', def: 'Advanced Persistent Threat — sustained, well-resourced, stealthy attacker, usually nation-state.', domain: 'D1', subObjective: 'D1.ThreatActors' },
  { id: 'fc-gdpr', term: 'GDPR', def: 'EU General Data Protection Regulation — privacy rights for EU residents; extraterritorial reach.', domain: 'D1', subObjective: 'D1.Laws.GDPR' },
  { id: 'fc-gdpr-rights', term: 'GDPR Data Subject Rights', def: 'Access, rectification, erasure, restriction, portability, objection, plus automated-decision rights.', domain: 'D1', subObjective: 'D1.Laws.GDPR' },
  { id: 'fc-data-controller', term: 'Data Controller', def: 'Entity determining the purposes and means of personal-data processing (GDPR).', domain: 'D1', subObjective: 'D1.Laws.GDPR' },
  { id: 'fc-data-processor', term: 'Data Processor', def: 'Entity processing personal data on behalf of a controller (GDPR).', domain: 'D1', subObjective: 'D1.Laws.GDPR' },
  { id: 'fc-hipaa', term: 'HIPAA', def: 'US law protecting Protected Health Information (PHI) held by covered entities and business associates.', domain: 'D1', subObjective: 'D1.Laws.HIPAA' },
  { id: 'fc-glba', term: 'GLBA', def: 'Gramm-Leach-Bliley Act — protects non-public financial information at US financial institutions.', domain: 'D1', subObjective: 'D1.Laws.GLBA' },
  { id: 'fc-ferpa', term: 'FERPA', def: 'US law protecting student educational records at institutions receiving federal funds.', domain: 'D1', subObjective: 'D1.Laws.FERPA' },
  { id: 'fc-sox', term: 'SOX', def: 'Sarbanes-Oxley Act — financial reporting and internal controls for publicly traded US companies.', domain: 'D1', subObjective: 'D1.Laws.SOX' },
  { id: 'fc-pci-dss', term: 'PCI-DSS', def: 'Payment Card Industry Data Security Standard — for any entity handling cardholder data.', domain: 'D1', subObjective: 'D1.Laws.PCI' },
  { id: 'fc-ccpa', term: 'CCPA', def: 'California Consumer Privacy Act — privacy rights for California residents.', domain: 'D1', subObjective: 'D1.Laws.GDPR' },
  { id: 'fc-coppa', term: 'COPPA', def: 'US Children\'s Online Privacy Protection Act — protects data of children under 13.', domain: 'D1', subObjective: 'D1.Laws.FERPA' },
  { id: 'fc-canon1', term: 'ISC2 Canon I', def: 'Protect society, the common good, necessary public trust and confidence, and the infrastructure.', domain: 'D1', subObjective: 'D1.Ethics.Canons' },
  { id: 'fc-canon2', term: 'ISC2 Canon II', def: 'Act honorably, honestly, justly, responsibly, and legally.', domain: 'D1', subObjective: 'D1.Ethics.Canons' },
  { id: 'fc-canon3', term: 'ISC2 Canon III', def: 'Provide diligent and competent service to principals.', domain: 'D1', subObjective: 'D1.Ethics.Canons' },
  { id: 'fc-canon4', term: 'ISC2 Canon IV', def: 'Advance and protect the profession.', domain: 'D1', subObjective: 'D1.Ethics.Canons' },
  { id: 'fc-aaa', term: 'AAA', def: 'Authentication, Authorization, Accounting (or Accountability) — pillars of identity management.', domain: 'D1', subObjective: 'D1.AAA' },
  { id: 'fc-authn', term: 'Authentication', def: 'Verifying that an entity is who or what it claims to be.', domain: 'D3', subObjective: 'D3.IAAA' },
  { id: 'fc-authz', term: 'Authorization', def: 'Granting an authenticated entity permission to perform an action on a resource.', domain: 'D3', subObjective: 'D3.IAAA' },
  { id: 'fc-accounting', term: 'Accounting', def: 'Logging actions to provide a record of who did what and when.', domain: 'D1', subObjective: 'D1.AAA' },
  { id: 'fc-accountability', term: 'Accountability', def: 'Ability to trace actions to a unique actor; supported by logging and unique identities.', domain: 'D1', subObjective: 'D1.AAA' },
  { id: 'fc-nonrep', term: 'Non-repudiation', def: 'Assurance the actor cannot credibly deny the action — typically via digital signatures.', domain: 'D1', subObjective: 'D1.NonRepudiation' },
  { id: 'fc-privacy', term: 'Privacy', def: 'Right of individuals to control collection and use of their personal information.', domain: 'D1', subObjective: 'D1.PrivacyVsSecurity' },
  { id: 'fc-adequate', term: 'Adequate Security', def: 'Security commensurate with the risk and magnitude of harm from loss/misuse of information.', domain: 'D1', subObjective: 'D1.Risk.Treatments' },
  { id: 'fc-classified', term: 'Classified Information', def: 'Data labeled per a classification scheme requiring handling rules per label.', domain: 'D5', subObjective: 'D5.Data.Classification' },
  { id: 'fc-biometric', term: 'Biometric', def: '"Something you are" — fingerprint, face, retina, voice — used as an auth factor.', domain: 'D3', subObjective: 'D3.AuthFactors' },

  // ============================================================
  // D2 — IR / BC / DR
  // ============================================================
  { id: 'fc-event', term: 'Event', def: 'Any observable occurrence in a system or network (e.g., a login, a file access).', domain: 'D2', subObjective: 'D2.IR.Terms' },
  { id: 'fc-incident', term: 'Incident', def: 'An adverse event or violation of security policy requiring response.', domain: 'D2', subObjective: 'D2.IR.Terms' },
  { id: 'fc-breach', term: 'Breach', def: 'Unauthorized disclosure or loss of control of sensitive data (e.g., PII, PHI).', domain: 'D2', subObjective: 'D2.IR.Terms' },
  { id: 'fc-intrusion', term: 'Intrusion', def: 'Unauthorized access into a system or network.', domain: 'D2', subObjective: 'D2.IR.Terms' },
  { id: 'fc-ir-prep', term: 'IR: Preparation', def: 'First IR phase — build the team, runbooks, training, and tooling before anything happens.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-ir-detect', term: 'IR: Detection & Analysis', def: 'Second IR phase — identify and scope incidents from alerts, logs, reports.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-ir-cer', term: 'IR: Containment, Eradication, Recovery', def: 'Third IR phase grouped — stop the bleeding, remove the cause, restore service.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-ir-post', term: 'IR: Post-Incident', def: 'Final IR phase — lessons learned, RCA documentation, control improvements.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-containment', term: 'Containment', def: 'Limiting an incident\'s scope — isolate hosts, block accounts, shut ports.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-eradication', term: 'Eradication', def: 'Removing the cause of an incident — malware, attacker accounts, vulnerabilities.', domain: 'D2', subObjective: 'D2.IR.Phases' },
  { id: 'fc-csirt', term: 'CSIRT', def: 'Computer Security Incident Response Team — cross-functional IR group.', domain: 'D2', subObjective: 'D2.IR.Team' },
  { id: 'fc-cert', term: 'CERT', def: 'Computer Emergency Response Team — synonymous with CSIRT in most contexts.', domain: 'D2', subObjective: 'D2.IR.Team' },
  { id: 'fc-coc', term: 'Chain of Custody', def: 'Documentation tracking who handled evidence, when, where, and why — required for legal admissibility.', domain: 'D2', subObjective: 'D2.IR.ChainOfCustody' },
  { id: 'fc-evidence', term: 'Evidence Handling', def: 'Procedures for collecting, preserving, transporting, and analyzing evidence without contamination.', domain: 'D2', subObjective: 'D2.IR.Evidence' },
  { id: 'fc-bcp', term: 'Business Continuity Plan', def: 'Plan to keep critical business functions running during a disruption.', domain: 'D2', subObjective: 'D2.BC.BIA' },
  { id: 'fc-drp', term: 'Disaster Recovery Plan', def: 'Plan to restore IT systems and data after a major outage.', domain: 'D2', subObjective: 'D2.DR.Sites' },
  { id: 'fc-bia', term: 'BIA', def: 'Business Impact Analysis — ranks processes by criticality and quantifies impact of loss.', domain: 'D2', subObjective: 'D2.BC.BIA' },
  { id: 'fc-rto', term: 'RTO', def: 'Recovery Time Objective — maximum acceptable downtime before recovery is complete.', domain: 'D2', subObjective: 'D2.BC.RTO_RPO' },
  { id: 'fc-rpo', term: 'RPO', def: 'Recovery Point Objective — maximum acceptable data loss measured in time.', domain: 'D2', subObjective: 'D2.BC.RTO_RPO' },
  { id: 'fc-mtd', term: 'MTD', def: 'Maximum Tolerable Downtime — absolute outage time the business can survive. RTO must be ≤ MTD.', domain: 'D2', subObjective: 'D2.BC.RTO_RPO' },
  { id: 'fc-wrt', term: 'WRT', def: 'Work Recovery Time — time to verify and reintegrate restored systems before users return.', domain: 'D2', subObjective: 'D2.BC.RTO_RPO' },
  { id: 'fc-mao', term: 'MAO', def: 'Maximum Acceptable Outage — synonym of MTD in many frameworks.', domain: 'D2', subObjective: 'D2.BC.RTO_RPO' },
  { id: 'fc-hot-site', term: 'Hot Site', def: 'Fully equipped DR site with current data — failover in minutes to hours.', domain: 'D2', subObjective: 'D2.DR.Sites' },
  { id: 'fc-warm-site', term: 'Warm Site', def: 'DR site with hardware and connectivity but stale or partial data; recovery in hours to days.', domain: 'D2', subObjective: 'D2.DR.Sites' },
  { id: 'fc-cold-site', term: 'Cold Site', def: 'DR site with power, HVAC, and space only — cheapest, slowest cutover.', domain: 'D2', subObjective: 'D2.DR.Sites' },
  { id: 'fc-cloud-site', term: 'Cloud DR Site', def: 'Recovery infrastructure provisioned on demand in a cloud provider.', domain: 'D2', subObjective: 'D2.DR.Sites' },
  { id: 'fc-full-backup', term: 'Full Backup', def: 'Backs up everything every time. Slowest to create, fastest to restore from.', domain: 'D2', subObjective: 'D2.DR.Backups' },
  { id: 'fc-inc-backup', term: 'Incremental Backup', def: 'Backs up only changes since the last backup of any kind. Fastest to create; restore needs full + all incrementals.', domain: 'D2', subObjective: 'D2.DR.Backups' },
  { id: 'fc-diff-backup', term: 'Differential Backup', def: 'Backs up all changes since the last FULL. Restore needs the last full + the latest differential.', domain: 'D2', subObjective: 'D2.DR.Backups' },
  { id: 'fc-tabletop', term: 'Tabletop Exercise', def: 'Discussion-based walkthrough of an IR/BC/DR scenario — no real systems touched.', domain: 'D2', subObjective: 'D2.Exercises' },
  { id: 'fc-functional-ex', term: 'Functional Exercise', def: 'Hands-on simulation testing actual response procedures and systems.', domain: 'D2', subObjective: 'D2.Exercises' },
  { id: 'fc-parallel-test', term: 'Parallel Test', def: 'Bring up the DR environment alongside production to verify it can carry the load.', domain: 'D2', subObjective: 'D2.Exercises' },
  { id: 'fc-call-tree', term: 'Call Tree', def: 'Notification cascade — each contact calls a defined set of others to reach everyone fast.', domain: 'D2', subObjective: 'D2.BC.CallTrees' },

  // ============================================================
  // D3 — Access Control
  // ============================================================
  { id: 'fc-subject', term: 'Subject', def: 'Active entity (user, process, device) that requests access to an object.', domain: 'D3', subObjective: 'D3.Fundamentals.SubjectObject' },
  { id: 'fc-object', term: 'Object', def: 'Passive resource (file, system, database) that a subject may access.', domain: 'D3', subObjective: 'D3.Fundamentals.SubjectObject' },
  { id: 'fc-rule', term: 'Access Rule', def: 'Policy or ACL specifying which subjects may perform which actions on which objects.', domain: 'D3', subObjective: 'D3.Fundamentals.SubjectObject' },
  { id: 'fc-iaaa', term: 'IAAA', def: 'Identification, Authentication, Authorization, Accountability — the access-control lifecycle.', domain: 'D3', subObjective: 'D3.IAAA' },
  { id: 'fc-identification', term: 'Identification', def: 'Claim of identity (e.g., entering a username). Precedes authentication.', domain: 'D3', subObjective: 'D3.IAAA' },
  { id: 'fc-factor-know', term: 'Knowledge Factor', def: '"Something you know" — password, PIN, security question.', domain: 'D3', subObjective: 'D3.AuthFactors' },
  { id: 'fc-factor-have', term: 'Possession Factor', def: '"Something you have" — hardware token, smartphone with TOTP, smartcard.', domain: 'D3', subObjective: 'D3.AuthFactors' },
  { id: 'fc-factor-are', term: 'Inherence Factor', def: '"Something you are" — biometric (fingerprint, face, retina, voice).', domain: 'D3', subObjective: 'D3.AuthFactors' },
  { id: 'fc-factor-where', term: 'Location Factor', def: '"Somewhere you are" — GPS, IP geolocation, network zone.', domain: 'D3', subObjective: 'D3.AuthFactors' },
  { id: 'fc-factor-do', term: 'Behavioral Factor', def: '"Something you do" — typing rhythm, gait, signature dynamics.', domain: 'D3', subObjective: 'D3.AuthFactors' },
  { id: 'fc-mfa', term: 'MFA', def: 'Multi-Factor Authentication — at least two of: know, have, are.', domain: 'D3', subObjective: 'D3.MFA' },
  { id: 'fc-2fa', term: '2FA', def: 'Two-Factor Authentication — exactly two factors from different categories.', domain: 'D3', subObjective: 'D3.MFA' },
  { id: 'fc-totp', term: 'TOTP', def: 'Time-based One-Time Password — short-lived 6-digit code synced via shared secret.', domain: 'D3', subObjective: 'D3.MFA' },
  { id: 'fc-hotp', term: 'HOTP', def: 'HMAC-based One-Time Password — counter-based; advances on each use.', domain: 'D3', subObjective: 'D3.MFA' },
  { id: 'fc-fido2', term: 'FIDO2 / WebAuthn', def: 'Modern phishing-resistant authentication using hardware-bound public keys.', domain: 'D3', subObjective: 'D3.MFA' },
  { id: 'fc-sso', term: 'SSO', def: 'Single Sign-On — one authentication grants access to multiple applications.', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-federation', term: 'Federation', def: 'Trust relationship allowing one identity provider\'s credentials to access another organization\'s resources.', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-saml', term: 'SAML', def: 'XML-based standard for exchanging authentication and authorization data between IdP and SP.', domain: 'D3', subObjective: 'D3.SSO.SAML' },
  { id: 'fc-oauth', term: 'OAuth 2.0', def: 'Authorization framework that lets an app access resources on behalf of a user without seeing their password.', domain: 'D3', subObjective: 'D3.SSO.OAuth_OIDC' },
  { id: 'fc-oidc', term: 'OpenID Connect', def: 'Authentication layer built on OAuth 2.0 — issues identity ID tokens (JWT).', domain: 'D3', subObjective: 'D3.SSO.OAuth_OIDC' },
  { id: 'fc-idp', term: 'IdP', def: 'Identity Provider — issues authentication assertions (e.g., Okta, Entra ID).', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-sp', term: 'Service Provider', def: 'Application that consumes identity assertions from an IdP.', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-jwt', term: 'JWT', def: 'JSON Web Token — signed token format used by OIDC and many APIs.', domain: 'D3', subObjective: 'D3.SSO.OAuth_OIDC' },
  { id: 'fc-kerberos', term: 'Kerberos', def: 'Ticket-based network authentication protocol using a Key Distribution Center.', domain: 'D3', subObjective: 'D3.Kerberos' },
  { id: 'fc-kdc', term: 'KDC', def: 'Kerberos Key Distribution Center — combines AS and TGS to issue tickets.', domain: 'D3', subObjective: 'D3.Kerberos' },
  { id: 'fc-tgt', term: 'TGT', def: 'Ticket-Granting Ticket — Kerberos credential proving identity; used to request service tickets.', domain: 'D3', subObjective: 'D3.Kerberos' },
  { id: 'fc-as', term: 'Authentication Server (Kerberos)', def: 'KDC component that issues the initial TGT after a user authenticates.', domain: 'D3', subObjective: 'D3.Kerberos' },
  { id: 'fc-tgs', term: 'TGS', def: 'Ticket Granting Service — KDC component that issues service-specific tickets using the TGT.', domain: 'D3', subObjective: 'D3.Kerberos' },
  { id: 'fc-ldap', term: 'LDAP', def: 'Lightweight Directory Access Protocol — query/modify directories (e.g., Active Directory).', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-radius', term: 'RADIUS', def: 'Remote Authentication Dial-In User Service — AAA for network access (Wi-Fi, VPN).', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-tacacs', term: 'TACACS+', def: 'Cisco AAA protocol for device administration; separates authn/authz/accounting.', domain: 'D3', subObjective: 'D3.SSO.Federation' },
  { id: 'fc-dac', term: 'DAC', def: 'Discretionary Access Control — owner decides who can access their resources.', domain: 'D3', subObjective: 'D3.Models.DAC' },
  { id: 'fc-mac', term: 'MAC', def: 'Mandatory Access Control — system enforces labels/classification; users cannot override.', domain: 'D3', subObjective: 'D3.Models.MAC' },
  { id: 'fc-rbac', term: 'RBAC', def: 'Role-Based Access Control — permissions tied to roles, users assigned to roles.', domain: 'D3', subObjective: 'D3.Models.RBAC' },
  { id: 'fc-abac', term: 'ABAC', def: 'Attribute-Based Access Control — policies use subject/resource/environment attributes.', domain: 'D3', subObjective: 'D3.Models.ABAC' },
  { id: 'fc-rubac', term: 'RuBAC', def: 'Rule-Based Access Control — decisions follow predefined rules (e.g., time-of-day, IP).', domain: 'D3', subObjective: 'D3.Models.ABAC' },
  { id: 'fc-leastpriv', term: 'Least Privilege', def: 'Grant only the minimum access needed to perform a role or task.', domain: 'D3', subObjective: 'D3.Principles.LeastPrivilege' },
  { id: 'fc-sod', term: 'Separation of Duties', def: 'Split critical actions across multiple people to prevent fraud and unilateral errors.', domain: 'D3', subObjective: 'D3.Principles.SeparationOfDuties' },
  { id: 'fc-ntk', term: 'Need to Know', def: 'Even with role, grant access only to data the user has a business reason to see.', domain: 'D3', subObjective: 'D3.Principles.NeedToKnow' },
  { id: 'fc-dual-control', term: 'Dual Control', def: 'Two-person integrity — both must act together to perform a sensitive operation.', domain: 'D3', subObjective: 'D3.Principles.DualControl' },
  { id: 'fc-pam', term: 'PAM', def: 'Privileged Access Management — vault, broker, audit privileged accounts and sessions.', domain: 'D3', subObjective: 'D3.PAM' },
  { id: 'fc-jit', term: 'Just-in-Time Provisioning', def: 'Elevate or grant privileges only for the duration of a specific task.', domain: 'D3', subObjective: 'D3.JIT' },
  { id: 'fc-session', term: 'Session Management', def: 'Issuing, tracking, and timing out user sessions; protecting session tokens from theft.', domain: 'D3', subObjective: 'D3.SessionMgmt' },
  { id: 'fc-acct-user', term: 'User Account', def: 'Standard account for an individual end user.', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-acct-service', term: 'Service Account', def: 'Non-interactive account used by applications or scripts.', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-acct-shared', term: 'Shared Account', def: 'Single account used by multiple people — discouraged (breaks accountability).', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-acct-guest', term: 'Guest Account', def: 'Limited-access account for visitors or temporary use.', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-acct-priv', term: 'Privileged Account', def: 'Elevated-rights account (admin, root) needing extra protection.', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-acct-system', term: 'System Account', def: 'Built-in OS account used for system processes.', domain: 'D3', subObjective: 'D3.AccountTypes' },
  { id: 'fc-provisioning', term: 'Provisioning', def: 'Creating an identity and granting initial access rights.', domain: 'D3', subObjective: 'D3.Lifecycle' },
  { id: 'fc-deprovisioning', term: 'Deprovisioning', def: 'Removing access when a user leaves the role or organization.', domain: 'D3', subObjective: 'D3.Lifecycle' },
  { id: 'fc-mantrap', term: 'Mantrap', def: 'Small room with two interlocked doors preventing tailgating.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-turnstile', term: 'Turnstile', def: 'Physical gate allowing only one person to pass per authentication.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-cctv', term: 'CCTV', def: 'Closed-Circuit Television — surveillance cameras (detective + deterrent).', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-badge', term: 'Badge Reader', def: 'Electronic reader controlling physical access via proximity card or smart card.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-bollard', term: 'Bollard', def: 'Vertical post blocking vehicle access to pedestrian or sensitive areas.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-fence', term: 'Fence', def: 'Perimeter barrier; height and reinforcement scale with required deterrence.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-lighting', term: 'Security Lighting', def: 'Illumination deterring intruders and supporting camera coverage.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-guard', term: 'Security Guard', def: 'Human physical control — deterrent, detective, and responsive.', domain: 'D3', subObjective: 'D3.Physical.Controls' },
  { id: 'fc-tailgating', term: 'Tailgating', def: 'Unauthorized person following an authorized person through a controlled door.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },
  { id: 'fc-piggybacking', term: 'Piggybacking', def: 'Like tailgating but with the authorized person\'s knowledge/consent.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },

  // ============================================================
  // D4 — Network Security
  // ============================================================
  { id: 'fc-osi', term: 'OSI Model', def: '7-layer reference model: Physical, Data Link, Network, Transport, Session, Presentation, Application.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-1', term: 'OSI Layer 1 — Physical', def: 'Bits on the wire — cables, NICs, signals, hubs.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-2', term: 'OSI Layer 2 — Data Link', def: 'Frames + MAC addressing. Switches and bridges. Ethernet, PPP.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-3', term: 'OSI Layer 3 — Network', def: 'Packets + IP addressing + routing. Routers. IPv4/IPv6, ICMP.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-4', term: 'OSI Layer 4 — Transport', def: 'Segments + ports + reliability. TCP, UDP.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-5', term: 'OSI Layer 5 — Session', def: 'Session establishment, maintenance, teardown. NetBIOS, RPC.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-6', term: 'OSI Layer 6 — Presentation', def: 'Encoding, compression, encryption. TLS often sits here in practice.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-osi-7', term: 'OSI Layer 7 — Application', def: 'Application protocols seen by users. HTTP, SMTP, DNS, FTP.', domain: 'D4', subObjective: 'D4.OSI.Layers' },
  { id: 'fc-tcpip', term: 'TCP/IP Model', def: '4-layer Internet model: Link, Internet, Transport, Application.', domain: 'D4', subObjective: 'D4.TCPIP' },
  { id: 'fc-tcp', term: 'TCP', def: 'Transmission Control Protocol — connection-oriented, reliable, ordered, with flow + congestion control.', domain: 'D4', subObjective: 'D4.TCPvsUDP' },
  { id: 'fc-udp', term: 'UDP', def: 'User Datagram Protocol — connectionless, unreliable, low-overhead. Used for DNS, VoIP, streaming.', domain: 'D4', subObjective: 'D4.TCPvsUDP' },
  { id: 'fc-3way', term: 'TCP 3-Way Handshake', def: 'SYN → SYN/ACK → ACK to establish a TCP connection.', domain: 'D4', subObjective: 'D4.TCP.Handshake' },
  { id: 'fc-4way-close', term: 'TCP 4-Way Close', def: 'FIN → ACK → FIN → ACK to gracefully tear down a TCP connection.', domain: 'D4', subObjective: 'D4.TCP.Handshake' },
  { id: 'fc-port-http', term: 'Port 80 (HTTP)', def: 'Plain HTTP. Use TLS (443) for anything sensitive.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-https', term: 'Port 443 (HTTPS)', def: 'HTTP over TLS. Default secure web traffic.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-ssh', term: 'Port 22 (SSH)', def: 'Secure Shell for encrypted remote admin and SFTP.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-telnet', term: 'Port 23 (Telnet)', def: 'Legacy remote-terminal protocol — cleartext; deprecated in favor of SSH.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-smtp', term: 'Port 25 (SMTP)', def: 'Simple Mail Transfer Protocol — server-to-server email delivery.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-dns', term: 'Port 53 (DNS)', def: 'Domain Name System — UDP 53 for queries, TCP 53 for zone transfers and large responses.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-dhcp', term: 'Port 67/68 (DHCP)', def: 'Dynamic Host Configuration Protocol — server 67, client 68.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-tftp', term: 'Port 69 (TFTP)', def: 'Trivial FTP — UDP, no authentication. Often used by network devices for image transfers.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-pop3', term: 'Port 110 (POP3)', def: 'Post Office Protocol v3 — email client retrieval. Use TLS (995) instead.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-imap', term: 'Port 143 (IMAP)', def: 'Internet Message Access Protocol — email retrieval keeping messages on the server. Use TLS (993).', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-snmp', term: 'Port 161/162 (SNMP)', def: 'Simple Network Management Protocol — 161 queries, 162 traps. Use v3 for security.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-ldap', term: 'Port 389 / 636 (LDAP/LDAPS)', def: 'LDAP directory queries; 636 is LDAP over TLS.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-smb', term: 'Port 445 (SMB)', def: 'Server Message Block — Windows file/print sharing.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-rdp', term: 'Port 3389 (RDP)', def: 'Remote Desktop Protocol — Windows graphical remote access.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-mssql', term: 'Port 1433 (MSSQL)', def: 'Microsoft SQL Server.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-mysql', term: 'Port 3306 (MySQL)', def: 'MySQL / MariaDB database.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-port-ntp', term: 'Port 123 (NTP)', def: 'Network Time Protocol — clock synchronization.', domain: 'D4', subObjective: 'D4.Ports' },
  { id: 'fc-ipv4', term: 'IPv4', def: '32-bit IP address space (~4.3B addresses). Dotted decimal.', domain: 'D4', subObjective: 'D4.IP.Versions' },
  { id: 'fc-ipv6', term: 'IPv6', def: '128-bit IP address space; written in 8 groups of 4 hex digits.', domain: 'D4', subObjective: 'D4.IP.Versions' },
  { id: 'fc-rfc1918', term: 'RFC1918', def: 'Private IPv4 ranges: 10/8, 172.16/12, 192.168/16. Not routable on the public Internet.', domain: 'D4', subObjective: 'D4.IP.RFC1918' },
  { id: 'fc-subnet', term: 'Subnet', def: 'Subdivision of an IP network defined by a subnet mask / prefix length.', domain: 'D4', subObjective: 'D4.Subnetting' },
  { id: 'fc-cidr', term: 'CIDR', def: 'Classless Inter-Domain Routing — /n notation indicating prefix length.', domain: 'D4', subObjective: 'D4.Subnetting' },
  { id: 'fc-nat', term: 'NAT', def: 'Network Address Translation — maps many private addresses to one public address.', domain: 'D4', subObjective: 'D4.NAT' },
  { id: 'fc-pat', term: 'PAT', def: 'Port Address Translation — NAT variant disambiguating sessions by source port.', domain: 'D4', subObjective: 'D4.NAT' },
  { id: 'fc-dhcp', term: 'DHCP', def: 'Dynamic Host Configuration Protocol — automatically assigns IP, mask, gateway, DNS.', domain: 'D4', subObjective: 'D4.DHCP' },
  { id: 'fc-dns', term: 'DNS', def: 'Domain Name System — translates names to IP addresses.', domain: 'D4', subObjective: 'D4.DNS.Basics' },
  { id: 'fc-dnssec', term: 'DNSSEC', def: 'DNS Security Extensions — digitally signs DNS responses to defeat tampering.', domain: 'D4', subObjective: 'D4.DNS.Attacks' },
  { id: 'fc-dns-hijack', term: 'DNS Hijacking', def: 'Redirecting DNS queries to attacker-controlled servers (often via router or registrar compromise).', domain: 'D4', subObjective: 'D4.DNS.Attacks' },
  { id: 'fc-dns-poison', term: 'DNS Cache Poisoning', def: 'Injecting forged records into a resolver\'s cache so users are sent to malicious sites.', domain: 'D4', subObjective: 'D4.DNS.Attacks' },
  { id: 'fc-icmp', term: 'ICMP', def: 'Internet Control Message Protocol — diagnostics (ping, traceroute). No ports.', domain: 'D4', subObjective: 'D4.ICMP' },
  { id: 'fc-arp', term: 'ARP', def: 'Address Resolution Protocol — maps IP addresses to MAC addresses on a LAN.', domain: 'D4', subObjective: 'D4.ARP' },
  { id: 'fc-arp-spoof', term: 'ARP Spoofing', def: 'Attacker sends forged ARP replies to associate their MAC with a victim IP — enables MitM.', domain: 'D4', subObjective: 'D4.ARP' },
  { id: 'fc-hub', term: 'Hub', def: 'Layer 1 device — repeats every frame to every port. Obsolete and insecure.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-switch', term: 'Switch', def: 'Layer 2 device — forwards frames to specific ports using a MAC address table.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-router', term: 'Router', def: 'Layer 3 device — moves packets between networks using IP and routing tables.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-bridge', term: 'Bridge', def: 'Layer 2 device joining two network segments while filtering by MAC.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-firewall', term: 'Firewall', def: 'Enforces a policy controlling traffic between networks of different trust levels.', domain: 'D4', subObjective: 'D4.Firewalls.Types' },
  { id: 'fc-fw-pkt', term: 'Packet-Filter Firewall', def: 'Decisions per packet using L3/L4 headers — no connection state.', domain: 'D4', subObjective: 'D4.Firewalls.Types' },
  { id: 'fc-fw-stateful', term: 'Stateful Firewall', def: 'Tracks connection state and admits only packets consistent with the established session.', domain: 'D4', subObjective: 'D4.Firewalls.Types' },
  { id: 'fc-fw-app', term: 'Application Proxy Firewall', def: 'Layer 7 firewall that terminates and inspects application traffic.', domain: 'D4', subObjective: 'D4.Firewalls.Types' },
  { id: 'fc-ngfw', term: 'NGFW', def: 'Next-Generation Firewall — stateful + DPI + IPS + app awareness + identity.', domain: 'D4', subObjective: 'D4.Firewalls.Types' },
  { id: 'fc-waf', term: 'WAF', def: 'Web Application Firewall — Layer 7 filtering for HTTP/S apps (SQLi, XSS).', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-proxy', term: 'Proxy', def: 'Intermediary that forwards traffic; can filter, cache, log, and enforce policy.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-rev-proxy', term: 'Reverse Proxy', def: 'Sits in front of servers; clients connect to it instead of the origin.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-lb', term: 'Load Balancer', def: 'Distributes traffic across servers; provides availability and scaling.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-ids', term: 'IDS', def: 'Intrusion Detection System — alerts on suspicious activity; does not block.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-ips', term: 'IPS', def: 'Intrusion Prevention System — in-line; actively blocks malicious traffic.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-siem', term: 'SIEM', def: 'Security Information and Event Management — collects, correlates, and alerts on logs.', domain: 'D5', subObjective: 'D5.SIEM' },
  { id: 'fc-soar', term: 'SOAR', def: 'Security Orchestration, Automation, Response — playbooks acting on SIEM alerts.', domain: 'D5', subObjective: 'D5.SIEM' },
  { id: 'fc-edr', term: 'EDR', def: 'Endpoint Detection and Response — agent-based monitoring + response on endpoints.', domain: 'D5', subObjective: 'D5.SIEM' },
  { id: 'fc-nac', term: 'NAC', def: 'Network Access Control — admits devices based on identity and posture before granting network access.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-honeypot', term: 'Honeypot', def: 'Decoy system designed to attract and study attackers.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-honeynet', term: 'Honeynet', def: 'Network of honeypots simulating a realistic environment.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-jump-host', term: 'Jump Server', def: 'Bastion host that brokers admin access to internal systems.', domain: 'D4', subObjective: 'D4.Devices.Layer' },
  { id: 'fc-vlan', term: 'VLAN', def: 'Virtual LAN — logical segmentation at Layer 2 on a switch.', domain: 'D4', subObjective: 'D4.VLAN' },
  { id: 'fc-segmentation', term: 'Network Segmentation', def: 'Dividing a network into zones to limit lateral movement and contain breaches.', domain: 'D4', subObjective: 'D4.Segmentation' },
  { id: 'fc-dmz', term: 'DMZ', def: 'Demilitarized Zone — semi-trusted network exposing internet-facing services while shielding internal.', domain: 'D4', subObjective: 'D4.DMZ' },
  { id: 'fc-screened-subnet', term: 'Screened Subnet', def: 'Modern name for a DMZ — a subnet between two firewalls.', domain: 'D4', subObjective: 'D4.DMZ' },
  { id: 'fc-zerotrust', term: 'Zero Trust', def: 'Never trust, always verify — no implicit trust based on network location.', domain: 'D4', subObjective: 'D4.ZeroTrust' },
  { id: 'fc-vpn', term: 'VPN', def: 'Virtual Private Network — encrypted tunnel across an untrusted network.', domain: 'D4', subObjective: 'D4.VPN' },
  { id: 'fc-vpn-s2s', term: 'Site-to-Site VPN', def: 'Permanent encrypted tunnel between two networks (often IPsec).', domain: 'D4', subObjective: 'D4.VPN' },
  { id: 'fc-vpn-ra', term: 'Remote-Access VPN', def: 'User device connects on demand into a corporate network.', domain: 'D4', subObjective: 'D4.VPN' },
  { id: 'fc-ipsec', term: 'IPsec', def: 'Network-layer encryption suite — AH (integrity) + ESP (confidentiality+integrity) + IKE (key exchange).', domain: 'D4', subObjective: 'D4.VPN' },
  { id: 'fc-tls', term: 'TLS', def: 'Transport Layer Security — encrypts traffic above TCP; basis of HTTPS.', domain: 'D4', subObjective: 'D4.VPN' },
  { id: 'fc-wep', term: 'WEP', def: 'Wired Equivalent Privacy — broken legacy Wi-Fi security; should not be used.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-wpa', term: 'WPA', def: 'Wi-Fi Protected Access — interim replacement for WEP.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-wpa2', term: 'WPA2', def: 'Wi-Fi Protected Access 2 — AES-CCMP. Long-standing standard until WPA3.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-wpa3', term: 'WPA3', def: 'Current Wi-Fi standard — SAE handshake replaces PSK; forward secrecy; defeats offline cracking.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-eap', term: 'EAP', def: 'Extensible Authentication Protocol — auth framework used by 802.1X / WPA-Enterprise.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-rogue-ap', term: 'Rogue AP', def: 'Unauthorized access point on a corporate network — bridges attacker into the LAN.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-evil-twin', term: 'Evil Twin', def: 'Attacker-controlled AP impersonating a legitimate SSID to harvest credentials.', domain: 'D4', subObjective: 'D4.Wireless' },
  { id: 'fc-iaas', term: 'IaaS', def: 'Infrastructure as a Service — provider gives VMs, storage, networking; you manage OS and up.', domain: 'D4', subObjective: 'D4.Cloud.Service' },
  { id: 'fc-paas', term: 'PaaS', def: 'Platform as a Service — provider manages OS and runtime; you ship code and data.', domain: 'D4', subObjective: 'D4.Cloud.Service' },
  { id: 'fc-saas', term: 'SaaS', def: 'Software as a Service — provider manages everything; you use the app and configure access.', domain: 'D4', subObjective: 'D4.Cloud.Service' },
  { id: 'fc-cloud-public', term: 'Public Cloud', def: 'Shared infrastructure rented by anyone (AWS, Azure, GCP).', domain: 'D4', subObjective: 'D4.Cloud.Deploy' },
  { id: 'fc-cloud-private', term: 'Private Cloud', def: 'Cloud dedicated to a single organization, on-prem or hosted.', domain: 'D4', subObjective: 'D4.Cloud.Deploy' },
  { id: 'fc-cloud-hybrid', term: 'Hybrid Cloud', def: 'Combination of public and private clouds with workload portability.', domain: 'D4', subObjective: 'D4.Cloud.Deploy' },
  { id: 'fc-cloud-community', term: 'Community Cloud', def: 'Shared by organizations with common concerns (e.g., gov agencies).', domain: 'D4', subObjective: 'D4.Cloud.Deploy' },
  { id: 'fc-shared-resp', term: 'Shared Responsibility', def: 'Cloud security is split — provider secures the cloud; customer secures what they put in it. Boundary varies by service model.', domain: 'D4', subObjective: 'D4.Cloud.SharedResp' },
  { id: 'fc-sdn', term: 'SDN', def: 'Software-Defined Networking — control plane separated from data plane; programmable via APIs.', domain: 'D4', subObjective: 'D4.SDN' },
  { id: 'fc-iot', term: 'IoT', def: 'Internet of Things — embedded devices, often with weak update / auth posture.', domain: 'D4', subObjective: 'D4.IoT' },
  { id: 'fc-ot', term: 'OT', def: 'Operational Technology — control systems for industrial processes; availability dominates.', domain: 'D4', subObjective: 'D4.OT_ICS' },
  { id: 'fc-ics', term: 'ICS', def: 'Industrial Control System — encompasses SCADA, DCS, PLCs.', domain: 'D4', subObjective: 'D4.OT_ICS' },
  { id: 'fc-scada', term: 'SCADA', def: 'Supervisory Control and Data Acquisition — monitors and controls geographically dispersed assets.', domain: 'D4', subObjective: 'D4.OT_ICS' },
  { id: 'fc-dos', term: 'DoS', def: 'Denial of Service — flooding a single source overwhelms a target.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-ddos', term: 'DDoS', def: 'Distributed DoS — many compromised hosts (botnet) attack simultaneously.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-syn-flood', term: 'SYN Flood', def: 'DoS by sending many SYNs without completing the handshake — fills connection tables.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-smurf', term: 'Smurf Attack', def: 'Amplifies ICMP echo via broadcast to drown a spoofed target.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-fraggle', term: 'Fraggle Attack', def: 'Like Smurf but using UDP echo packets.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-pod', term: 'Ping of Death', def: 'Sends a malformed/oversized ICMP packet to crash legacy stacks.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-teardrop', term: 'Teardrop', def: 'Sends overlapping IP fragments to crash legacy reassembly code.', domain: 'D4', subObjective: 'D4.Attacks.DoS' },
  { id: 'fc-mitm', term: 'MitM', def: 'Man-in-the-Middle (a.k.a. on-path) — attacker sits between two parties intercepting traffic.', domain: 'D4', subObjective: 'D4.Attacks.MitM' },
  { id: 'fc-onpath', term: 'On-Path Attack', def: 'Current term for MitM — modern usage discourages "man-in-the-middle" phrasing.', domain: 'D4', subObjective: 'D4.Attacks.MitM' },
  { id: 'fc-replay', term: 'Replay Attack', def: 'Attacker captures a valid message and re-sends it to gain access.', domain: 'D4', subObjective: 'D4.Attacks.MitM' },
  { id: 'fc-soceng', term: 'Social Engineering', def: 'Manipulating people into divulging info or performing actions that compromise security.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },
  { id: 'fc-phishing', term: 'Phishing', def: 'Mass-targeted social engineering, usually email, to harvest credentials or deliver malware.', domain: 'D4', subObjective: 'D4.Attacks.Phishing' },
  { id: 'fc-spear', term: 'Spear Phishing', def: 'Targeted phishing crafted for a specific person or small group using personalized info.', domain: 'D4', subObjective: 'D4.Attacks.Phishing' },
  { id: 'fc-whaling', term: 'Whaling', def: 'Spear phishing aimed at high-value targets like executives.', domain: 'D4', subObjective: 'D4.Attacks.Phishing' },
  { id: 'fc-vishing', term: 'Vishing', def: 'Voice phishing — phone-based social engineering.', domain: 'D4', subObjective: 'D4.Attacks.Phishing' },
  { id: 'fc-smishing', term: 'Smishing', def: 'SMS phishing — text-message based.', domain: 'D4', subObjective: 'D4.Attacks.Phishing' },
  { id: 'fc-pretexting', term: 'Pretexting', def: 'Fabricating a believable scenario to extract info or actions.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },
  { id: 'fc-baiting', term: 'Baiting', def: 'Leaving an enticing object (e.g., a USB drive) for a victim to take and use.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },
  { id: 'fc-watering-hole', term: 'Watering Hole', def: 'Compromise a site the target group visits, infecting them on arrival.', domain: 'D4', subObjective: 'D4.Attacks.SocialEng' },
  { id: 'fc-virus', term: 'Virus', def: 'Malware that attaches to a host file and spreads when the host runs.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-worm', term: 'Worm', def: 'Self-replicating malware that spreads across networks without user action.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-trojan', term: 'Trojan', def: 'Malware disguised as legitimate software; runs when the user opens it.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-rat', term: 'RAT', def: 'Remote Access Trojan — gives attacker remote control of a victim system.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-rootkit', term: 'Rootkit', def: 'Stealth malware modifying the OS to hide its own presence and other tools.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-ransomware', term: 'Ransomware', def: 'Encrypts victim data and demands payment for the decryption key.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-spyware', term: 'Spyware', def: 'Covertly observes user activity (keystrokes, screenshots, browsing).', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-adware', term: 'Adware', def: 'Software that pushes ads — often bundled with other unwanted software.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-logic-bomb', term: 'Logic Bomb', def: 'Malicious code that triggers when a condition is met (date, event, user action).', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-fileless', term: 'Fileless Malware', def: 'Runs entirely in memory using legitimate tools (PowerShell, WMI); leaves few disk artifacts.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-keylogger', term: 'Keylogger', def: 'Captures keystrokes — can be software or hardware.', domain: 'D4', subObjective: 'D4.Attacks.Malware' },
  { id: 'fc-bruteforce', term: 'Brute Force', def: 'Trying every possible password; defeated by length and account lockouts.', domain: 'D4', subObjective: 'D4.Attacks.Password' },
  { id: 'fc-dictionary', term: 'Dictionary Attack', def: 'Tries words from a list; defeated by complex unguessable passwords.', domain: 'D4', subObjective: 'D4.Attacks.Password' },
  { id: 'fc-rainbow', term: 'Rainbow Table', def: 'Precomputed hash → password lookup table; defeated by salting.', domain: 'D4', subObjective: 'D4.Attacks.Password' },
  { id: 'fc-cred-stuff', term: 'Credential Stuffing', def: 'Replaying breached username/password pairs against other sites that reuse them.', domain: 'D4', subObjective: 'D4.Attacks.Password' },
  { id: 'fc-pw-spray', term: 'Password Spraying', def: 'Trying one common password against many accounts to avoid per-account lockouts.', domain: 'D4', subObjective: 'D4.Attacks.Password' },
  { id: 'fc-sqli', term: 'SQL Injection', def: 'Exploiting unsanitized input concatenated into SQL. Use parameterized queries.', domain: 'D4', subObjective: 'D4.Attacks.Injection' },
  { id: 'fc-xss', term: 'XSS', def: 'Cross-Site Scripting — injecting client-side script into pages other users see.', domain: 'D4', subObjective: 'D4.Attacks.Injection' },
  { id: 'fc-csrf', term: 'CSRF', def: 'Cross-Site Request Forgery — tricking an authenticated user\'s browser into making unwanted requests.', domain: 'D4', subObjective: 'D4.Attacks.Injection' },
  { id: 'fc-cmd-inj', term: 'Command Injection', def: 'Executing shell commands via unsanitized input passed to system calls.', domain: 'D4', subObjective: 'D4.Attacks.Injection' },
  { id: 'fc-supply-chain', term: 'Supply Chain Attack', def: 'Compromising a trusted vendor or component to reach downstream targets.', domain: 'D4', subObjective: 'D4.Attacks.SupplyChain' },
  { id: 'fc-zero-day', term: 'Zero-Day', def: 'Vulnerability unknown to the vendor (and unpatched) at the time of exploitation.', domain: 'D4', subObjective: 'D4.Attacks.SupplyChain' },

  // ============================================================
  // D5 — Security Operations
  // ============================================================
  { id: 'fc-data-lifecycle', term: 'Data Lifecycle', def: 'Create → Store → Use → Share → Archive → Destroy.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-create', term: 'Data Create', def: 'First lifecycle stage — classify at creation, set ownership.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-store', term: 'Data Store', def: 'Lifecycle stage — encrypt at rest, enforce access controls per classification.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-use', term: 'Data Use', def: 'Lifecycle stage — enforce least privilege; log access for accountability.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-share', term: 'Data Share', def: 'Lifecycle stage — encrypt in transit, verify recipient need-to-know.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-archive', term: 'Data Archive', def: 'Lifecycle stage — long-term cold storage per retention policy.', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-destroy', term: 'Data Destroy', def: 'Lifecycle stage — sanitize per classification (clear / purge / destroy).', domain: 'D5', subObjective: 'D5.Data.Lifecycle' },
  { id: 'fc-data-at-rest', term: 'Data at Rest', def: 'Stored on a disk or backup medium. Protect with encryption + access controls.', domain: 'D5', subObjective: 'D5.Data.States' },
  { id: 'fc-data-in-transit', term: 'Data in Transit', def: 'Moving across a network. Protect with TLS, IPsec, encrypted protocols.', domain: 'D5', subObjective: 'D5.Data.States' },
  { id: 'fc-data-in-use', term: 'Data in Use', def: 'Being processed in memory. Protect with access controls, enclave technologies, memory hygiene.', domain: 'D5', subObjective: 'D5.Data.States' },
  { id: 'fc-data-class', term: 'Data Classification', def: 'Labeling data by sensitivity to drive protection requirements.', domain: 'D5', subObjective: 'D5.Data.Classification' },
  { id: 'fc-data-class-gov', term: 'Gov Classification', def: 'Top Secret > Secret > Confidential > Unclassified.', domain: 'D5', subObjective: 'D5.Data.Classification' },
  { id: 'fc-data-class-comm', term: 'Commercial Classification', def: 'Highly Restricted > Restricted > Internal > Public.', domain: 'D5', subObjective: 'D5.Data.Classification' },
  { id: 'fc-data-labeling', term: 'Data Labeling', def: 'Marking documents and records with their classification.', domain: 'D5', subObjective: 'D5.Data.Labeling' },
  { id: 'fc-sanitize-clear', term: 'Clearing', def: 'Overwriting media so data cannot be recovered with standard tools. Reusable for same level.', domain: 'D5', subObjective: 'D5.Data.Sanitization' },
  { id: 'fc-sanitize-purge', term: 'Purging', def: 'Removing data so it cannot be recovered even with lab tools (degauss, crypto-erase).', domain: 'D5', subObjective: 'D5.Data.Sanitization' },
  { id: 'fc-sanitize-destroy', term: 'Destruction', def: 'Physically destroying media (shred, incinerate, pulverize).', domain: 'D5', subObjective: 'D5.Data.Sanitization' },
  { id: 'fc-degauss', term: 'Degaussing', def: 'Strong magnetic field that scrambles magnetic media — only effective for magnetic disks/tapes.', domain: 'D5', subObjective: 'D5.Data.MediaDestruction' },
  { id: 'fc-crypto-erase', term: 'Cryptographic Erase', def: 'Destroying the encryption key so encrypted data becomes unrecoverable.', domain: 'D5', subObjective: 'D5.Data.MediaDestruction' },
  { id: 'fc-shred', term: 'Shredding', def: 'Mechanically destroying media (paper or media shredders).', domain: 'D5', subObjective: 'D5.Data.MediaDestruction' },
  { id: 'fc-incinerate', term: 'Incineration', def: 'Burning media to ash — irrecoverable destruction.', domain: 'D5', subObjective: 'D5.Data.MediaDestruction' },
  { id: 'fc-retention', term: 'Retention Policy', def: 'How long data must be kept (regulatory + business needs) and when it must be destroyed.', domain: 'D5', subObjective: 'D5.Data.Retention' },
  { id: 'fc-logging', term: 'Logging', def: 'Recording events to enable monitoring, accountability, and forensic investigation.', domain: 'D5', subObjective: 'D5.Logging.WhatToLog' },
  { id: 'fc-log-integrity', term: 'Log Integrity', def: 'Tamper-resistance — write-once, off-host shipping, hash chains, signing.', domain: 'D5', subObjective: 'D5.Logging.Integrity' },
  { id: 'fc-syslog', term: 'Syslog', def: 'Standard for forwarding log messages; centralizes logs from many hosts.', domain: 'D5', subObjective: 'D5.Logging.Integrity' },
  { id: 'fc-encryption', term: 'Encryption', def: 'Reversible transformation of plaintext into ciphertext using a key.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-symenc', term: 'Symmetric Encryption', def: 'Same key encrypts and decrypts — fast; key distribution is the challenge.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-asymenc', term: 'Asymmetric Encryption', def: 'Key pair: public encrypts/verifies, private decrypts/signs.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-aes', term: 'AES', def: 'Advanced Encryption Standard — fast, secure symmetric block cipher (128/192/256-bit keys).', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-des', term: 'DES', def: 'Legacy 56-bit symmetric cipher — broken. Do not use.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-3des', term: '3DES', def: 'Triple-DES — three DES rounds. Slow, deprecated.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-blowfish', term: 'Blowfish', def: 'Bruce Schneier\'s 64-bit block cipher. Twofish is the modern successor.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-twofish', term: 'Twofish', def: 'AES finalist — 128-bit block, 128/192/256-bit keys.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-rc4', term: 'RC4', def: 'Stream cipher historically used in WEP and early TLS. Broken; do not use.', domain: 'D5', subObjective: 'D5.Crypto.Symmetric' },
  { id: 'fc-rsa', term: 'RSA', def: 'Asymmetric algorithm — keys based on factoring large primes.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-dsa', term: 'DSA', def: 'Digital Signature Algorithm — based on discrete logarithm problem.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-ecc', term: 'ECC', def: 'Elliptic Curve Cryptography — small keys with high security; common in modern TLS.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-elgamal', term: 'ElGamal', def: 'Asymmetric encryption based on discrete logs; used in PGP.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-dh', term: 'Diffie-Hellman', def: 'Key exchange — two parties agree on a shared secret over an insecure channel.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-ecdhe', term: 'ECDHE', def: 'Ephemeral Diffie-Hellman over elliptic curves — provides forward secrecy.', domain: 'D5', subObjective: 'D5.Crypto.Asymmetric' },
  { id: 'fc-hash', term: 'Hashing', def: 'One-way function producing a fixed-size digest; verifies integrity.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-md5', term: 'MD5', def: 'Legacy 128-bit hash — collision-broken. Do not use for security.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-sha1', term: 'SHA-1', def: '160-bit hash — collision attacks demonstrated. Phased out.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-sha2', term: 'SHA-2', def: 'Family of hashes (SHA-224/256/384/512). Current general-purpose standard.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-sha3', term: 'SHA-3', def: 'Newer hash family with different internal design from SHA-2 (Keccak).', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-salt', term: 'Salt', def: 'Random per-password value mixed into the hash to defeat rainbow tables.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-pepper', term: 'Pepper', def: 'Secret value (often server-wide) mixed in addition to salt; stored separately.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-bcrypt', term: 'bcrypt', def: 'Deliberately slow password hash; tunable work factor.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-scrypt', term: 'scrypt', def: 'Memory-hard password hash designed to resist GPU/ASIC cracking.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-argon2', term: 'Argon2', def: 'Modern memory-hard password hash; winner of PHC competition.', domain: 'D5', subObjective: 'D5.Crypto.Hashing' },
  { id: 'fc-hmac', term: 'HMAC', def: 'Hash-based Message Authentication Code — combines a secret key with a hash for integrity + authenticity.', domain: 'D5', subObjective: 'D5.Crypto.HMAC' },
  { id: 'fc-digital-sig', term: 'Digital Signature', def: 'Signer\'s private key encrypts a hash of the message; verifies integrity + origin + non-repudiation.', domain: 'D5', subObjective: 'D5.Crypto.DigitalSig' },
  { id: 'fc-pki', term: 'PKI', def: 'Public Key Infrastructure — CAs, certificates, revocation, trust chains.', domain: 'D5', subObjective: 'D5.PKI.Basics' },
  { id: 'fc-ca', term: 'Certificate Authority', def: 'Trusted entity that issues and signs digital certificates.', domain: 'D5', subObjective: 'D5.PKI.Basics' },
  { id: 'fc-ra', term: 'Registration Authority', def: 'Verifies identity of subjects before a CA issues a certificate.', domain: 'D5', subObjective: 'D5.PKI.Basics' },
  { id: 'fc-crl', term: 'CRL', def: 'Certificate Revocation List — periodically published list of revoked certs.', domain: 'D5', subObjective: 'D5.PKI.Basics' },
  { id: 'fc-ocsp', term: 'OCSP', def: 'Online Certificate Status Protocol — real-time check of certificate revocation.', domain: 'D5', subObjective: 'D5.PKI.Basics' },
  { id: 'fc-cert-dv', term: 'DV Certificate', def: 'Domain Validation — proves control of the domain; cheapest, fastest issuance.', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-ov', term: 'OV Certificate', def: 'Organization Validation — proves the organization\'s legal existence.', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-ev', term: 'EV Certificate', def: 'Extended Validation — strictest validation; legacy "green bar" in browsers.', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-wild', term: 'Wildcard Certificate', def: 'Covers all subdomains of a base domain (e.g., *.example.com).', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-san', term: 'SAN Certificate', def: 'Subject Alternative Name — one cert covering multiple specific hostnames.', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-self', term: 'Self-Signed Certificate', def: 'Issuer is the subject — not trusted by default; use only in test or trusted internal contexts.', domain: 'D5', subObjective: 'D5.PKI.CertTypes' },
  { id: 'fc-cert-chain', term: 'Certificate Chain', def: 'Sequence from end-entity cert to a trusted root CA via intermediates.', domain: 'D5', subObjective: 'D5.PKI.Validation' },
  { id: 'fc-key-escrow', term: 'Key Escrow', def: 'Storing a copy of a key with a trusted third party for recovery in defined circumstances.', domain: 'D5', subObjective: 'D5.KeyMgmt' },
  { id: 'fc-hsm', term: 'HSM', def: 'Hardware Security Module — tamper-resistant device for key generation, storage, and crypto ops.', domain: 'D5', subObjective: 'D5.HSM' },
  { id: 'fc-baseline', term: 'Baseline', def: 'Documented reference configuration used to detect drift from the expected state.', domain: 'D5', subObjective: 'D5.Config.Baseline' },
  { id: 'fc-cis', term: 'CIS Benchmarks', def: 'Center for Internet Security configuration baselines for hardening common platforms.', domain: 'D5', subObjective: 'D5.Config.Baseline' },
  { id: 'fc-stig', term: 'STIG', def: 'Security Technical Implementation Guide — US DoD hardening guidance.', domain: 'D5', subObjective: 'D5.Config.Baseline' },
  { id: 'fc-drift', term: 'Configuration Drift', def: 'Divergence from the baseline; triggers investigation and remediation.', domain: 'D5', subObjective: 'D5.Config.Baseline' },
  { id: 'fc-harden', term: 'Hardening', def: 'Reducing attack surface — patch, disable unused services, restrict accounts, secure configs.', domain: 'D5', subObjective: 'D5.Config.Hardening' },
  { id: 'fc-patch', term: 'Patch Management', def: 'Process of identifying, testing, and applying software updates to remediate vulnerabilities.', domain: 'D5', subObjective: 'D5.Patch' },
  { id: 'fc-change-mgmt', term: 'Change Management', def: 'Formal process for proposing, approving, implementing, and reviewing changes.', domain: 'D5', subObjective: 'D5.Change' },
  { id: 'fc-rfc', term: 'RFC (change)', def: 'Request for Change — formal proposal documented and reviewed.', domain: 'D5', subObjective: 'D5.Change' },
  { id: 'fc-cab', term: 'CAB', def: 'Change Advisory Board — group that reviews and approves changes.', domain: 'D5', subObjective: 'D5.Change' },
  { id: 'fc-rollback', term: 'Rollback Plan', def: 'Pre-defined steps to revert a change if it fails.', domain: 'D5', subObjective: 'D5.Change' },
  { id: 'fc-vt-r', term: 'Vulnerability vs Threat vs Risk', def: 'Weakness vs actor/event vs probability×impact when they combine.', domain: 'D5', subObjective: 'D5.VulnThreatRisk' },
  { id: 'fc-awareness', term: 'Security Awareness', def: 'Ongoing training that teaches users how to recognize and resist threats.', domain: 'D5', subObjective: 'D5.Training.Awareness' },
  { id: 'fc-phish-sim', term: 'Phishing Simulation', def: 'Controlled fake phishing emails sent to staff; measures and shapes click behavior.', domain: 'D5', subObjective: 'D5.Training.Awareness' },
  { id: 'fc-aup', term: 'AUP', def: 'Acceptable Use Policy — rules for using company systems, data, and networks.', domain: 'D5', subObjective: 'D5.Training.AUP_BYOD' },
  { id: 'fc-byod', term: 'BYOD', def: 'Bring Your Own Device — policy enabling personal devices to access corporate resources.', domain: 'D5', subObjective: 'D5.Training.AUP_BYOD' },
  { id: 'fc-mdm', term: 'MDM', def: 'Mobile Device Management — enforces policy on managed mobile devices.', domain: 'D5', subObjective: 'D5.Training.AUP_BYOD' },
  { id: 'fc-clean-desk', term: 'Clean Desk Policy', def: 'Requires users to clear sensitive material from desks when away.', domain: 'D5', subObjective: 'D5.Training.CleanDesk' },
  { id: 'fc-shoulder-surf', term: 'Shoulder Surfing', def: 'Observing someone\'s screen or keyboard to steal info.', domain: 'D5', subObjective: 'D5.Training.CleanDesk' },
  { id: 'fc-dumpster', term: 'Dumpster Diving', def: 'Recovering sensitive info from discarded materials. Defended by shredding.', domain: 'D5', subObjective: 'D5.Training.CleanDesk' },
];

export const FLASHCARDS_BY_DOMAIN = FLASHCARDS.reduce<Record<string, Flashcard[]>>((acc, c) => {
  (acc[c.domain] ||= []).push(c);
  return acc;
}, {});
