import { DomainId } from '../lib/storage';

export type Objective = {
  id: string;
  domain: DomainId;
  title: string;
  refModuleId?: string;
};

export const OBJECTIVES: Objective[] = [
  // ============ D1 Security Principles ============
  { id: 'D1.CIA.Definition', domain: 'D1', title: 'CIA triad definition', refModuleId: 'd1-cia' },
  { id: 'D1.CIA.DAD', domain: 'D1', title: 'DAD: opposites of CIA', refModuleId: 'd1-cia' },
  { id: 'D1.DataTypes.PII', domain: 'D1', title: 'PII identification', refModuleId: 'd1-cia' },
  { id: 'D1.DataTypes.PHI', domain: 'D1', title: 'PHI identification', refModuleId: 'd1-cia' },
  { id: 'D1.DataTypes.SPI', domain: 'D1', title: 'SPI / sensitive personal info', refModuleId: 'd1-cia' },
  { id: 'D1.Risk.Formula', domain: 'D1', title: 'Risk = likelihood × impact', refModuleId: 'd1-risk' },
  { id: 'D1.Risk.Qualitative', domain: 'D1', title: 'Qualitative risk analysis', refModuleId: 'd1-risk' },
  { id: 'D1.Risk.Quantitative', domain: 'D1', title: 'Quantitative risk (ALE/SLE/ARO/EF)', refModuleId: 'd1-risk' },
  { id: 'D1.Risk.Treatments', domain: 'D1', title: 'Risk treatments: accept/avoid/mitigate/transfer', refModuleId: 'd1-risk' },
  { id: 'D1.Controls.Categories', domain: 'D1', title: 'Control categories: physical/technical/administrative', refModuleId: 'd1-controls' },
  { id: 'D1.Controls.Functions', domain: 'D1', title: 'Control functions: preventive/detective/corrective/deterrent/compensating/directive', refModuleId: 'd1-controls' },
  { id: 'D1.Governance.Hierarchy', domain: 'D1', title: 'Governance hierarchy: regs → standards → policies → procedures', refModuleId: 'd1-gov' },
  { id: 'D1.Governance.Frameworks', domain: 'D1', title: 'Frameworks: NIST CSF, ISO 27001/27002, SOC 1/2/3', refModuleId: 'd1-gov' },
  { id: 'D1.ThreatActors', domain: 'D1', title: 'Threat actor types', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.GDPR', domain: 'D1', title: 'GDPR and data-subject rights', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.HIPAA', domain: 'D1', title: 'HIPAA', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.GLBA', domain: 'D1', title: 'GLBA', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.FERPA', domain: 'D1', title: 'FERPA', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.SOX', domain: 'D1', title: 'SOX', refModuleId: 'd1-gov' },
  { id: 'D1.Laws.PCI', domain: 'D1', title: 'PCI-DSS', refModuleId: 'd1-gov' },
  { id: 'D1.Ethics.Canons', domain: 'D1', title: 'ISC2 Code of Ethics canon order', refModuleId: 'd1-ethics' },
  { id: 'D1.AAA', domain: 'D1', title: 'AAA: authentication, authorization, accounting', refModuleId: 'd1-gov' },
  { id: 'D1.NonRepudiation', domain: 'D1', title: 'Non-repudiation', refModuleId: 'd1-gov' },
  { id: 'D1.PrivacyVsSecurity', domain: 'D1', title: 'Privacy vs security distinction', refModuleId: 'd1-gov' },

  // ============ D2 IR / BC / DR ============
  { id: 'D2.IR.Phases', domain: 'D2', title: 'IR phases (NIST 4-phase / 6-phase)', refModuleId: 'd2-ir' },
  { id: 'D2.IR.Terms', domain: 'D2', title: 'Event vs incident vs breach vs intrusion', refModuleId: 'd2-ir' },
  { id: 'D2.IR.Team', domain: 'D2', title: 'CSIRT / CERT team composition', refModuleId: 'd2-ir' },
  { id: 'D2.IR.ChainOfCustody', domain: 'D2', title: 'Chain of custody', refModuleId: 'd2-ir' },
  { id: 'D2.IR.Evidence', domain: 'D2', title: 'Evidence handling', refModuleId: 'd2-ir' },
  { id: 'D2.BC.BIA', domain: 'D2', title: 'Business Impact Analysis', refModuleId: 'd2-bc' },
  { id: 'D2.BC.RTO_RPO', domain: 'D2', title: 'RPO / RTO / MTD / WRT', refModuleId: 'd2-dr' },
  { id: 'D2.BC.CallTrees', domain: 'D2', title: 'Notification systems / call trees', refModuleId: 'd2-bc' },
  { id: 'D2.DR.Sites', domain: 'D2', title: 'DR sites: hot/warm/cold/cloud', refModuleId: 'd2-dr' },
  { id: 'D2.DR.Backups', domain: 'D2', title: 'Backup strategies: full/incremental/differential', refModuleId: 'd2-dr' },
  { id: 'D2.Exercises', domain: 'D2', title: 'Tabletop vs functional exercises', refModuleId: 'd2-bc' },

  // ============ D3 Access Control ============
  { id: 'D3.Fundamentals.SubjectObject', domain: 'D3', title: 'Subjects, objects, rules', refModuleId: 'd3-fund' },
  { id: 'D3.IAAA', domain: 'D3', title: 'IAAA: identification/authentication/authorization/accountability', refModuleId: 'd3-fund' },
  { id: 'D3.AuthFactors', domain: 'D3', title: 'Authentication factor categories', refModuleId: 'd3-logical' },
  { id: 'D3.MFA', domain: 'D3', title: 'Multi-factor authentication', refModuleId: 'd3-logical' },
  { id: 'D3.SSO.Federation', domain: 'D3', title: 'SSO vs federation', refModuleId: 'd3-logical' },
  { id: 'D3.SSO.SAML', domain: 'D3', title: 'SAML', refModuleId: 'd3-logical' },
  { id: 'D3.SSO.OAuth_OIDC', domain: 'D3', title: 'OAuth / OIDC', refModuleId: 'd3-logical' },
  { id: 'D3.Kerberos', domain: 'D3', title: 'Kerberos KDC/TGT', refModuleId: 'd3-logical' },
  { id: 'D3.Models.DAC', domain: 'D3', title: 'DAC', refModuleId: 'd3-logical' },
  { id: 'D3.Models.MAC', domain: 'D3', title: 'MAC', refModuleId: 'd3-logical' },
  { id: 'D3.Models.RBAC', domain: 'D3', title: 'RBAC', refModuleId: 'd3-logical' },
  { id: 'D3.Models.ABAC', domain: 'D3', title: 'ABAC', refModuleId: 'd3-logical' },
  { id: 'D3.Principles.LeastPrivilege', domain: 'D3', title: 'Least privilege', refModuleId: 'd3-logical' },
  { id: 'D3.Principles.SeparationOfDuties', domain: 'D3', title: 'Separation of duties', refModuleId: 'd3-logical' },
  { id: 'D3.Principles.NeedToKnow', domain: 'D3', title: 'Need to know', refModuleId: 'd3-logical' },
  { id: 'D3.Principles.DualControl', domain: 'D3', title: 'Dual control / two-person integrity', refModuleId: 'd3-logical' },
  { id: 'D3.PAM', domain: 'D3', title: 'Privileged Access Management', refModuleId: 'd3-logical' },
  { id: 'D3.JIT', domain: 'D3', title: 'Just-in-time provisioning', refModuleId: 'd3-logical' },
  { id: 'D3.SessionMgmt', domain: 'D3', title: 'Session management', refModuleId: 'd3-logical' },
  { id: 'D3.AccountTypes', domain: 'D3', title: 'Account types: user/service/shared/guest/privileged', refModuleId: 'd3-logical' },
  { id: 'D3.Lifecycle', domain: 'D3', title: 'Provisioning lifecycle', refModuleId: 'd3-logical' },
  { id: 'D3.Physical.Controls', domain: 'D3', title: 'Physical access controls', refModuleId: 'd3-physical' },
  { id: 'D3.DefenseInDepth', domain: 'D3', title: 'Defense in depth', refModuleId: 'd3-fund' },

  // ============ D4 Network Security ============
  { id: 'D4.OSI.Layers', domain: 'D4', title: 'OSI 7 layers', refModuleId: 'd4-basics' },
  { id: 'D4.TCPIP', domain: 'D4', title: 'TCP/IP 4-layer model', refModuleId: 'd4-basics' },
  { id: 'D4.TCP.Handshake', domain: 'D4', title: 'TCP 3-way handshake / 4-way close', refModuleId: 'd4-basics' },
  { id: 'D4.TCPvsUDP', domain: 'D4', title: 'TCP vs UDP', refModuleId: 'd4-basics' },
  { id: 'D4.Ports', domain: 'D4', title: 'Common ports', refModuleId: 'd4-basics' },
  { id: 'D4.IP.Versions', domain: 'D4', title: 'IPv4 vs IPv6', refModuleId: 'd4-basics' },
  { id: 'D4.IP.RFC1918', domain: 'D4', title: 'RFC1918 private ranges', refModuleId: 'd4-basics' },
  { id: 'D4.Subnetting', domain: 'D4', title: 'Subnetting concepts', refModuleId: 'd4-basics' },
  { id: 'D4.NAT', domain: 'D4', title: 'NAT', refModuleId: 'd4-basics' },
  { id: 'D4.DHCP', domain: 'D4', title: 'DHCP', refModuleId: 'd4-basics' },
  { id: 'D4.DNS.Basics', domain: 'D4', title: 'DNS basics', refModuleId: 'd4-basics' },
  { id: 'D4.DNS.Attacks', domain: 'D4', title: 'DNS attacks + DNSSEC', refModuleId: 'd4-threats' },
  { id: 'D4.ICMP', domain: 'D4', title: 'ICMP', refModuleId: 'd4-basics' },
  { id: 'D4.ARP', domain: 'D4', title: 'ARP + spoofing', refModuleId: 'd4-threats' },
  { id: 'D4.Devices.Layer', domain: 'D4', title: 'Hub/switch/router/firewall/proxy/LB/IDS/IPS/WAF/SIEM/NAC/honeypot/jumphost', refModuleId: 'd4-tools' },
  { id: 'D4.Firewalls.Types', domain: 'D4', title: 'Firewall types', refModuleId: 'd4-tools' },
  { id: 'D4.VLAN', domain: 'D4', title: 'VLANs', refModuleId: 'd4-tools' },
  { id: 'D4.Segmentation', domain: 'D4', title: 'Segmentation', refModuleId: 'd4-tools' },
  { id: 'D4.DMZ', domain: 'D4', title: 'DMZ', refModuleId: 'd4-tools' },
  { id: 'D4.ZeroTrust', domain: 'D4', title: 'Zero trust', refModuleId: 'd4-tools' },
  { id: 'D4.VPN', domain: 'D4', title: 'VPN: site-to-site vs remote, IPsec vs SSL/TLS', refModuleId: 'd4-tools' },
  { id: 'D4.Wireless', domain: 'D4', title: 'Wireless: WEP/WPA/WPA2/WPA3, EAP, RADIUS, rogue/evil twin', refModuleId: 'd4-tools' },
  { id: 'D4.Cloud.Service', domain: 'D4', title: 'IaaS/PaaS/SaaS', refModuleId: 'd4-tools' },
  { id: 'D4.Cloud.Deploy', domain: 'D4', title: 'Public/private/hybrid/community', refModuleId: 'd4-tools' },
  { id: 'D4.Cloud.SharedResp', domain: 'D4', title: 'Shared responsibility', refModuleId: 'd4-tools' },
  { id: 'D4.SDN', domain: 'D4', title: 'Software-defined networking', refModuleId: 'd4-tools' },
  { id: 'D4.IoT', domain: 'D4', title: 'IoT risks', refModuleId: 'd4-threats' },
  { id: 'D4.OT_ICS', domain: 'D4', title: 'OT / ICS / SCADA risks', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.DoS', domain: 'D4', title: 'DoS / DDoS family', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.MitM', domain: 'D4', title: 'MitM / on-path / replay', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.SocialEng', domain: 'D4', title: 'Social engineering taxonomy', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.Phishing', domain: 'D4', title: 'Phishing/spear/whaling/vishing/smishing/pretext', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.Malware', domain: 'D4', title: 'Malware families', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.Password', domain: 'D4', title: 'Password attacks', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.Injection', domain: 'D4', title: 'Injection: SQLi/XSS/CSRF/command', refModuleId: 'd4-threats' },
  { id: 'D4.Attacks.SupplyChain', domain: 'D4', title: 'Supply chain attacks', refModuleId: 'd4-threats' },

  // ============ D5 Security Operations ============
  { id: 'D5.Data.Lifecycle', domain: 'D5', title: 'Data lifecycle', refModuleId: 'd5-data' },
  { id: 'D5.Data.States', domain: 'D5', title: 'Data states: rest / transit / use', refModuleId: 'd5-data' },
  { id: 'D5.Data.Classification', domain: 'D5', title: 'Classification schemes', refModuleId: 'd5-data' },
  { id: 'D5.Data.Labeling', domain: 'D5', title: 'Data labeling', refModuleId: 'd5-data' },
  { id: 'D5.Data.Sanitization', domain: 'D5', title: 'Clear / purge / destroy', refModuleId: 'd5-data' },
  { id: 'D5.Data.MediaDestruction', domain: 'D5', title: 'Degauss / crypto-erase / shred / incinerate', refModuleId: 'd5-data' },
  { id: 'D5.Data.Retention', domain: 'D5', title: 'Retention policies', refModuleId: 'd5-data' },
  { id: 'D5.Logging.WhatToLog', domain: 'D5', title: 'What to log', refModuleId: 'd5-log' },
  { id: 'D5.Logging.Integrity', domain: 'D5', title: 'Log integrity / syslog', refModuleId: 'd5-log' },
  { id: 'D5.SIEM', domain: 'D5', title: 'SIEM correlation', refModuleId: 'd5-log' },
  { id: 'D5.Crypto.Symmetric', domain: 'D5', title: 'Symmetric ciphers (AES/DES/3DES/Blowfish/Twofish/RC4)', refModuleId: 'd5-crypto' },
  { id: 'D5.Crypto.Asymmetric', domain: 'D5', title: 'Asymmetric (RSA/DSA/ECC/ElGamal/DH)', refModuleId: 'd5-crypto' },
  { id: 'D5.Crypto.Hashing', domain: 'D5', title: 'Hashing (SHA-2/3, MD5 broken, salt, pepper)', refModuleId: 'd5-crypto' },
  { id: 'D5.Crypto.HMAC', domain: 'D5', title: 'HMAC', refModuleId: 'd5-crypto' },
  { id: 'D5.Crypto.DigitalSig', domain: 'D5', title: 'Digital signatures', refModuleId: 'd5-crypto' },
  { id: 'D5.PKI.Basics', domain: 'D5', title: 'PKI: CA, RA, CRL, OCSP', refModuleId: 'd5-crypto' },
  { id: 'D5.PKI.CertTypes', domain: 'D5', title: 'Certificate types: DV/OV/EV, wildcard, SAN, self-signed', refModuleId: 'd5-crypto' },
  { id: 'D5.PKI.Validation', domain: 'D5', title: 'Certificate chain validation', refModuleId: 'd5-crypto' },
  { id: 'D5.KeyMgmt', domain: 'D5', title: 'Key escrow / management', refModuleId: 'd5-crypto' },
  { id: 'D5.HSM', domain: 'D5', title: 'HSM', refModuleId: 'd5-crypto' },
  { id: 'D5.Config.Baseline', domain: 'D5', title: 'Baselines / drift / CIS / STIG', refModuleId: 'd5-config' },
  { id: 'D5.Config.Hardening', domain: 'D5', title: 'Hardening', refModuleId: 'd5-config' },
  { id: 'D5.Patch', domain: 'D5', title: 'Patch management', refModuleId: 'd5-config' },
  { id: 'D5.Change', domain: 'D5', title: 'Change management: RFC / CAB / rollback', refModuleId: 'd5-config' },
  { id: 'D5.VulnThreatRisk', domain: 'D5', title: 'Vulnerability vs threat vs risk', refModuleId: 'd5-config' },
  { id: 'D5.Training.Awareness', domain: 'D5', title: 'Security awareness training', refModuleId: 'd5-aware' },
  { id: 'D5.Training.AUP_BYOD', domain: 'D5', title: 'AUP / BYOD policy', refModuleId: 'd5-aware' },
  { id: 'D5.Training.CleanDesk', domain: 'D5', title: 'Clean desk policy', refModuleId: 'd5-aware' },
];

export const OBJECTIVE_BY_ID: Record<string, Objective> = Object.fromEntries(OBJECTIVES.map((o) => [o.id, o]));
